feat: localization for chat bot micro app
Etiya/etiya_chatbot_flutter pull request #7
Opened 2022-06-20 10:05 UTC by Abhishek01039

2022-06-20 10:15 UTC, EnesKaraosman requested changes

2022-06-20 10:15 UTC, EnesKaraosman commented on lib/src/localization/localization_delegate.dart
> +class ToggPluginAppLocalizationsDelegate
This **package** is not a plugin, so ToggMicroAppXXX might be more appropriate? @Abhishek01039

2022-06-20 10:15 UTC, EnesKaraosman commented on lib/src/localization/i10n.dart
> +  static String getFlag(String code) {
We don't need flags currently..

2022-06-20 10:15 UTC, EnesKaraosman commented on lib/src/localization/generated/app_localizations_tr.dart
> +  String get login => 'Giriş yapmak';
pls change it to 'Giriş'

2022-06-20 10:15 UTC, EnesKaraosman commented on lib/src/localization/generated/app_localizations_tr.dart
> +  String get enter_non_empty_password => 'Boş olmayan şifreyi girin';
'Lütfen şifre alanını boş bırakmayınız'

2022-06-20 10:15 UTC, EnesKaraosman commented on lib/src/localization/generated/app_localizations_tr.dart
> +  String get email_address => 'E-posta Adresi';
'Email'

2022-06-20 10:15 UTC, EnesKaraosman commented on lib/src/localization/generated/app_localizations_tr.dart
> +  String get enter_valid_email => 'Geçerli e-posta girin';
'Geçerli bir email giriniz'

2022-06-20 10:15 UTC, EnesKaraosman commented on l10n.yaml
> +arb-dir: lib/src/localization
does localization package automatically generates under `localization/generated` folder, or you need to specifically define here?

2022-06-20 10:27 UTC, Abhishek01039 commented on l10n.yaml
> +arb-dir: lib/src/localization
Need to drag and drop the generated files to lib/localization/generated files

2022-06-20 10:30 UTC, Abhishek01039 commented on lib/src/localization/localization_delegate.dart
> +class ToggPluginAppLocalizationsDelegate
`ChatBotAppLocalizationsDelegate` how about this @EnesKaraosman ?

2022-06-27 06:55 UTC, EnesKaraosman commented on README.md
> +### Localisation
Typo: `Localization`

2022-06-27 06:59 UTC, merged